### ISSUE TITLE
Way out of date

### ISSUE THREAD

**Issue by Jurryaany** [frog23/TomScottMap#15]
It's okay if its dead but I really liked this project :(

**Comment by frog23** [comment]
It is not dead, I just had a lot of other things that take up time and attention, so I couldn't spend as much time on this hobby project of mine. I have been meaning to publish some updates for quite some time now and so this might actually get met to take care of this in the next weeks, but not until Monday. I have just pushed the empty template data for the latest videos (about half a year), so the videos are at least visible in the review interface. Thanks for the reminder. This kind of nudge was just what I needed.

**Comment by Jurryaany** [comment]
I understand buddy, don't worry about it! Unfortunately I don't have the time either or I would have picked it up. My backlog is miles already but I just happened to remember this project falling asleep one evening.

Don't overwork yourself, this project is cool but there's more important things in life.

Cheers!

**Comment by frog23** [comment]
fixed in ea7f844.
