### ISSUE TITLE
Where is the new video , link with Tom Scott Map Updater seem to be broken again?

### ISSUE THREAD

**Issue by Plushb9rry** [frog23/TomScottMap#35]
https://www.youtube.com/watch?v=yqciKS_N0K8

**Comment by frog23** [comment]
For some yet unknown reason my host has turned my virtual server off on Friday. All the parameters looked good. Anyways, I have restarted it and it promptly ran the script and added the last two videos. 
I should set up a monitoring script that informs me, if this ever happens again. Anyways, thanks for letting me know.
